select * from customer;

select * from ADDRESS;

select FIRST_NAME, LAST_NAME, ADDRESS, PHONE
from CUSTOMER join ADDRESS
on CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--Q what if I want to see customer table address_id information too.

select FIRST_NAME, LAST_NAME,CUSTOMER.ADDRESS_ID , ADDRESS.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER join ADDRESS
on CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID
order by CUSTOMER.ADDRESS_ID;

--Table Aliases
--Customer --C
--Employees --E
--Address --A

select FIRST_NAME, LAST_NAME, C.ADDRESS_ID , A.ADDRESS_ID, ADDRESS, PHONE
from CUSTOMER C join ADDRESS A
on C.ADDRESS_ID = A.ADDRESS_ID
order by C.ADDRESS_ID;


--INNER JOIN and JOIN is the same logic
SELECT FIRST_NAME,LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID,ADDRESS,PHONE
FROM CUSTOMER C INNER JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;

/*
    LEFT OUTER JOIN / LEFT JOIN
    --it will give matching part between two tables + unique for LEFT table
    --the order of the table is important
 */
SELECT FIRST_NAME,LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID,ADDRESS,PHONE
FROM CUSTOMER C left outer JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;

/*
    RIGHT OUTER JOIN / RIGHT JOIN
    --it will give matching part + unique for RIGHT table
    --the order of table is important
 */

SELECT FIRST_NAME,LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID,ADDRESS,PHONE
FROM CUSTOMER C right outer JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;


SELECT FIRST_NAME,LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID,ADDRESS,PHONE
FROM CUSTOMER C full JOIN ADDRESS A
ON C.ADDRESS_ID = A.ADDRESS_ID;

--LEFT JOIN WITH WHERE
SELECT *
FROM CUSTOMER C FULL JOIN ADDRESS A
on A.ADDRESS_ID = C.ADDRESS_ID
WHERE A.ADDRESS_ID IS NULL OR c.ADDRESS_ID IS NULL ;

